## Numpy Practice Notebook

In [2]:
!pip install numpy


In [144]:
import numpy as np

In [4]:
arr1=[2,3],

b=4
arr=(arr1*b)
arr

([2, 3], [2, 3], [2, 3], [2, 3])

# Creating a numpy array Using np.array

In [111]:
arr1=np.array([22,33,44])
arr1



array([22, 33, 44])

In [112]:
type(arr1)
# type of numpy array is numpy.ndarray

numpy.ndarray

In [113]:
arr2=np.array([22,5,21])
arr2

array([22,  5, 21])

In [114]:
type(arr2)

numpy.ndarray

In [115]:
# Indexing 
arr1[1]

33

In [116]:
arr2[2]

21

## Operations on numpy array
* np.dot is used to find the  dot product of an array, it will multiply element by element like 1st element of an 1st array with the 1st element of 2nd array and give the result by adding all of them & it will take less time from normaal (1st *2nd ).sum()function

In [117]:
np.dot(arr1,arr2)

1573

In [118]:
(arr1*arr2).sum()

1573

In [130]:
example_1=np.array([-4.0,-5.0,-1.0])
example_1



array([-4., -5., -1.])

In [131]:
example_2=np.array([-3.0,-5.0,-1.0])
example_2

array([-3., -5., -1.])

In [132]:
(example_1*example_2).sum()

38.0

In [133]:
np.dot(example_1,example_2)

38.0

In [134]:
example_3=np.array([2,6,14])
example_3

array([ 2,  6, 14])

In [135]:
example_4=np.array([1,3,7])
example_4

array([1, 3, 7])

In [136]:
example_3.shape
# Used to find Shape of an array

(3,)

In [137]:
np.dot(example_3,example_4)

118

In [138]:
(example_3*example_4).sum()

118


## Multi-dimensional Array

## 2-Dimensional Array 

In [139]:
climate_data=np.array([[22,33,43],
                      [33,11,33],
                      [66,22,55],
                      [66,44,55]])
climate_data

array([[22, 33, 43],
       [33, 11, 33],
       [66, 22, 55],
       [66, 44, 55]])

In [23]:
climate_data.shape
# 4 rows & 3columns

(4, 3)

In [24]:
climate_data

array([[22, 33, 43],
       [33, 11, 33],
       [66, 22, 55],
       [66, 44, 55]])

In [25]:
weights.dtype

dtype('int32')

In [26]:
climate_data.dtype

dtype('int32')

In [27]:
# Matrix Multiplication
np.matmul(climate_data,weights)

array([1552, 1474, 2717, 2827])

In [91]:
arr2=(climate_data@weights)
arr2.shape

(4,)

In [29]:
arr1=np.array([[[2,3,4],
             [9,2,3],
             [1,2,3],
             [2,4,6]]])
arr1

array([[[2, 3, 4],
        [9, 2, 3],
        [1, 2, 3],
        [2, 4, 6]]])

In [104]:
arr1.shape

(2, 3)

In [89]:
arr2=(arr1@weights)

In [92]:
arr2.shape

(4,)

In [110]:
arr3=np.concatenate((climate_data,arr1),axis=0)
arr3

array([[22, 33, 43],
       [33, 11, 33],
       [66, 22, 55],
       [66, 44, 55],
       [34, 34, 34],
       [34, 34, 34]])

* np.concatenate() is used to add two arrays,The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation.

## 3-Dimensional Array

In [32]:
arr1=np.array([[[1,2,3,4,5],
               [6,7,8,9,0],
               [3,4,5,6,7]],
               
                
               [[1,2,3,4,5],
               [6,7,8,9,0],
                [3,4,5,6,7]],
              
              [[1,2,3,4,5],
              [6,7,8,9,0],
              [3,4,5,6,7]],
              
              [[1,2,3,4,5],
              [6,7,8,9,0],
              [3,4,5,6,7]]])
arr1

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [3, 4, 5, 6, 7]]])

In [34]:
arr1.shape

(4, 3, 5)

In [35]:
arr1.dtype

dtype('int32')

## 4-Dimensional Array

In [36]:
arr1=np.array([[[[1,2,3,4,5],
                [6,7,8,9,0],
                [2,3,4,5,6]],
                
               [[1,2,3,4,5],
               [6,7,8,9,0],
               [2,3,4,5,6]],
               
               [[1,2,3,4,5],
               [6,7,8,9,0],
               [2,3,4,5,6]]]])
arr1


array([[[[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 0],
         [2, 3, 4, 5, 6]],

        [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 0],
         [2, 3, 4, 5, 6]],

        [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 0],
         [2, 3, 4, 5, 6]]]])

In [37]:
arr1.shape

(1, 3, 3, 5)

In [38]:
arr2=np.array([[[[1,2,3,4],
              [5,6,7,8]],
               
              [[1,2,3,4],
              [5,6,7,8]]]])
               
               
arr2

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [40]:
arr2.shape

(1, 2, 2, 4)

## Arithmetic Operation on Numpy's Array
* Numpy arrays support different type of arithmetic operation like (+,-,*,/) . we can also do any  arithmetic operation with single number  

In [41]:
arr1=np.array([[11,22,33,44],
              [55,66,77,88]])
arr1

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [42]:
arr2=np.array([[22,33,44,11],
              [33,44,55,66]])
arr2

array([[22, 33, 44, 11],
       [33, 44, 55, 66]])

In [43]:
(arr1+arr2)

array([[ 33,  55,  77,  55],
       [ 88, 110, 132, 154]])

In [44]:
(arr1-arr2)

array([[-11, -11, -11,  33],
       [ 22,  22,  22,  22]])

In [45]:
(arr1*arr2)

array([[ 242,  726, 1452,  484],
       [1815, 2904, 4235, 5808]])

In [46]:
(arr1%arr2)

array([[11, 22, 33,  0],
       [22, 22, 22, 22]], dtype=int32)

In [47]:
(arr1/arr2)

array([[0.5       , 0.66666667, 0.75      , 4.        ],
       [1.66666667, 1.5       , 1.4       , 1.33333333]])

In [48]:
(arr1//arr2)

array([[0, 0, 0, 4],
       [1, 1, 1, 1]], dtype=int32)

In [49]:
# Adding Scelar Number
(arr1+2)

array([[13, 24, 35, 46],
       [57, 68, 79, 90]])

In [50]:
(arr1*3)

array([[ 33,  66,  99, 132],
       [165, 198, 231, 264]])

## Array Broadcasting 

* Array Broadcasting means adding two different arrays with different number of dimensions but have same shapes.

In [51]:
arr1=np.array([[2,4,6,8,10],
              [12,14,16,18,20]])
arr1

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [52]:
arr2=np.array([22,24,26,28,30])
arr2

array([22, 24, 26, 28, 30])

In [53]:
(arr1+arr2)

array([[24, 28, 32, 36, 40],
       [34, 38, 42, 46, 50]])

## Array Comparison



In [54]:
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])


In [55]:
(arr1>arr2)

array([False, False, False, False])

In [56]:
(arr1<arr2)

array([ True,  True,  True,  True])

In [57]:
(arr1==arr2)

array([False, False, False, False])

In [58]:
(arr1!=arr2)

array([ True,  True,  True,  True])

In [59]:
(arr1>=arr2)

array([False, False, False, False])

In [60]:
(arr1<=arr2)

array([ True,  True,  True,  True])

## Array Indexing and Slicing

In [61]:
arr1=np.array([[[[1,2,3,4,5],
                [6,7,8,9,0],
                [2,3,4,5,6]],
                
               [[11,12,13,14,15],
               [16,17,18,19,20],
               [21,23,24,25,26]],
               
               [[31,32,33,34,35],
               [36,37,38,39,40],
               [32,33,34,35,36]]]])
arr1

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9,  0],
         [ 2,  3,  4,  5,  6]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [21, 23, 24, 25, 26]],

        [[31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40],
         [32, 33, 34, 35, 36]]]])

In [62]:
arr1.shape

(1, 3, 3, 5)

In [63]:
arr1[0,0,1,4]

0

In [64]:
arr1[0,1,2,3]

25

In [65]:
arr1[0,2,1,0]

36

In [66]:
arr1[0,2]

array([[31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [32, 33, 34, 35, 36]])

In [67]:
arr1[0,0,2,3]

5

In [68]:
arr1[0,1]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 23, 24, 25, 26]])

In [69]:
# Subarray Using Ranges
arr1[0,0:2,1,0:1]

array([[ 6],
       [16]])

In [70]:
arr1[0,0:1,0:2,3]

array([[4, 9]])

## Some Quick Ways to Create a Numpy Array

* np.zeros:-for making array of all Zeros
* np.ones :- for making array of all 1
* np.eye:-for making   identity array 
* np.random.rand:- for making array With uniformly distributed random numbers
* np.random.randn :- for making array With normally (Gaussian) distributed random numbers 
* np.full:-for making array With Same given Values
* np.arange:-for making array With Some ranging 
* np.linspace:-for making array With equqlly space Values in a range
* np.reshape :- is used to change the shape of an array 


In [71]:
# for making array of all Zeros
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [72]:
# for making array of all 1
np.ones([2,2,4,5])

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [73]:
# for making identity array
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
# for making array With Some random Values
np.random.rand(2,4,1,2)

array([[[[0.30758583, 0.75400887]],

        [[0.19431091, 0.71754382]],

        [[0.09471132, 0.5500246 ]],

        [[0.05751926, 0.38648453]]],


       [[[0.23421937, 0.92690112]],

        [[0.93950362, 0.36746568]],

        [[0.56910064, 0.79301538]],

        [[0.39641594, 0.89378044]]]])

In [75]:
np.random.randn(2,4,3,2)

array([[[[-0.38061819, -0.32842874],
         [ 0.62366124, -0.93357346],
         [ 0.95437866, -0.18302858]],

        [[-0.13350753,  0.11435153],
         [ 0.17915754,  0.72804747],
         [-0.87175298, -1.38319421]],

        [[-1.18221467, -0.73079635],
         [-0.0591867 , -0.10120668],
         [ 0.51897392,  1.53702979]],

        [[ 0.3833529 ,  1.08282519],
         [ 1.28353763, -0.42638714],
         [ 0.26908222, -0.32135895]]],


       [[[ 1.24112394,  0.40734774],
         [ 0.24814322,  1.8141601 ],
         [ 0.4249462 ,  0.57824041]],

        [[ 0.46356886, -0.11499331],
         [ 0.3092073 ,  0.59621207],
         [-0.39296018,  1.04785957]],

        [[-1.14311443, -0.5999446 ],
         [-0.79592667,  0.58865046],
         [-0.29098633,  0.93629689]],

        [[-0.64332872, -0.27984091],
         [-0.78860641,  1.09821239],
         [ 0.44075537,  0.71238433]]]])

- Diffrence  Between rand and randn is rand gives uniformly distributed random numbers whose values lies between 0 and 1 whereas randn gives normally (Gaussian) distributed random numbers whose values theoretically lies between -Infinity to Infinity

In [76]:
#  for making array With Same given Values
np.full([2,2,2,3],34)

array([[[[34, 34, 34],
         [34, 34, 34]],

        [[34, 34, 34],
         [34, 34, 34]]],


       [[[34, 34, 34],
         [34, 34, 34]],

        [[34, 34, 34],
         [34, 34, 34]]]])

In [77]:
# for making array With Some ranging 
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [78]:
# for making array With equqlly space Values in a range
np.linspace(2,64,32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52.,
       54., 56., 58., 60., 62., 64.])

In [79]:

np.linspace(2,64,16)

array([ 2.        ,  6.13333333, 10.26666667, 14.4       , 18.53333333,
       22.66666667, 26.8       , 30.93333333, 35.06666667, 39.2       ,
       43.33333333, 47.46666667, 51.6       , 55.73333333, 59.86666667,
       64.        ])

In [80]:
np.linspace(2,64,10)

array([ 2.        ,  8.88888889, 15.77777778, 22.66666667, 29.55555556,
       36.44444444, 43.33333333, 50.22222222, 57.11111111, 64.        ])

In [84]:
arr1=np.full([2,3],34)
arr1

array([[34, 34, 34],
       [34, 34, 34]])

In [85]:
arr1.reshape([3,2])

array([[34, 34],
       [34, 34],
       [34, 34]])

## Note:-

* np.genfromtxt() is used to read the files
* np.savetxt() is used to write into file or make a file 